In [1]:
import pandas as pd
import numpy as np
import torch


## PREPARATION OF THE DATA
biometry = pd.read_csv('/data/kpusteln/Fetal-RL/data_preparation/org_data/biometry_org.csv')

femur_biometry = biometry[['ID', 'FL', 'femur_ps']]
abdomen_biometry = biometry[['ID', 'AC', 'abdomen_ps']]
head_biometry = biometry[['ID', 'HC', 'head_ps']]

femur_biometry['ID'] = femur_biometry['ID'].astype(str)
abdomen_biometry['ID'] = abdomen_biometry['ID'].astype(str)
head_biometry['ID'] = head_biometry['ID'].astype(str)

for i in range(len(femur_biometry)):
    idx = femur_biometry.loc[i, 'ID']
    new_idx = idx + '_3'
    femur_biometry.loc[i, 'ID'] = new_idx
    
for i in range(len(abdomen_biometry)):
    idx = abdomen_biometry.loc[i, 'ID']
    new_idx = idx + '_2'
    abdomen_biometry.loc[i, 'ID'] = new_idx
    
for i in range(len(head_biometry)):
    idx = head_biometry.loc[i, 'ID']
    new_idx = idx + '_1'
    head_biometry.loc[i, 'ID'] = new_idx

/data/kpusteln/my-envs/swin/lib/python3.7/site-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
/data/kpusteln/my-envs/swin/lib/python3.7/site-packages/ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/data/kpusteln/my-envs/swin/lib/python3.7/site-packages/ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app
/data/kpusteln/my-envs/swin/lib/python3.7/site-packages/pandas/core/indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

In [2]:
head_biometry = head_biometry.rename(columns={'HC': 'measure', 'head_ps': 'ps', 'ID': 'video'})
abdomen_biometry = abdomen_biometry.rename(columns={'AC': 'measure', 'abdomen_ps': 'ps', 'ID': 'video'})
femur_biometry = femur_biometry.rename(columns={'FL': 'measure', 'femur_ps': 'ps', 'ID': 'video'})

In [3]:
new_data = pd.concat([femur_biometry, abdomen_biometry, head_biometry], axis=0)

In [4]:
data = pd.read_csv('/data/kpusteln/Fetal-RL/data_preparation/outputs/labels_corrected.csv')
data

           index  Class  video
0          1_1_1      1    1_1
1          1_1_2      1    1_1
2          1_1_3      1    1_1
3          1_1_4      1    1_1
4          1_1_5      1    1_1
...          ...    ...    ...
261760  708_3_75      5  708_3
261761  708_3_76      5  708_3
261762  708_3_77      5  708_3
261763  708_3_78      5  708_3
261764  708_3_79      5  708_3

[261765 rows x 3 columns]

In [5]:
data = pd.read_csv('/data/kpusteln/Fetal-RL/data_preparation/outputs/labels_corrected.csv')
merged = pd.merge(data, new_data, on='video')

In [7]:
merged.to_csv('/data/kpusteln/Fetal-RL/data_preparation/outputs/biometry_all_clean.csv', index=False)

In [25]:
biometry = pd.read_csv('/data/kpusteln/Fetal-RL/data_preparation/org_data/biometry_org.csv')

In [26]:
biometry

      ID     HC   head_ps     AC  abdomen_ps    FL  femur_ps
0      1  20.19  0.096716  17.74    0.110422  4.15  0.096809
1      2  19.19  0.107914  15.63    0.113594  3.59  0.076084
2      3  25.19  0.121011  22.21    0.147919  5.38  0.147919
3      4  23.98  0.129155  21.01    0.156729  4.80  0.115368
4      5  17.10  0.102237  15.87    0.094373  3.20  0.087999
..   ...    ...       ...    ...         ...   ...       ...
596  703  31.48  0.194965  30.38    0.225223  6.16  0.180680
597  704  19.71  0.139701  17.72    0.132349  4.01  0.089929
598  705  24.34  0.159498  21.59    0.215154  4.83  0.167642
599  706  22.59  0.217095  21.02    0.217095  4.56  0.217095
600  707  30.83  0.180680  29.90    0.180680  6.41  0.136138

[601 rows x 7 columns]

In [27]:
biometry_abdomen = biometry[['ID', 'AC', 'abdomen_ps']]
biometry_head = biometry[['ID', 'HC', 'head_ps']]
biometry_femur = biometry[['ID', 'FL', 'femur_ps']]

In [28]:
data = pd.read_csv('/data/kpusteln/Fetal-RL/data_preparation/outputs/labels_corrected.csv')

In [29]:
data

           index  Class  video
0          1_1_1      1    1_1
1          1_1_2      1    1_1
2          1_1_3      1    1_1
3          1_1_4      1    1_1
4          1_1_5      1    1_1
...          ...    ...    ...
261760  708_3_75      5  708_3
261761  708_3_76      5  708_3
261762  708_3_77      5  708_3
261763  708_3_78      5  708_3
261764  708_3_79      5  708_3

[261765 rows x 3 columns]

In [30]:
head = data['index'].str.split('_').str[1] == '1'
abdomen = data['index'].str.split('_').str[1] == '2'
femur = data['index'].str.split('_').str[1] == '3'

In [31]:
data_abdomen = data[abdomen]
data_head = data[head]
data_femur = data[femur]

In [32]:
# abdomen
ID = data_abdomen['index'].str.split('_').str[0]
ID = ID.astype(int)
data_abdomen['ID'] = ID
data_merged = pd.merge(data_abdomen, biometry_abdomen, on='ID')
data_merged.drop(columns = 'ID', inplace=True)
data_merged.to_csv('/data/kpusteln/Fetal-RL/data_preparation/data_biometry/abdomen_biometry.csv', index=False)

/tmp/ipykernel_738255/2364610853.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_abdomen['ID'] = ID

In [33]:
# head
ID = data_head['index'].str.split('_').str[0]
ID = ID.astype(int)
data_head['ID'] = ID
data_merged = pd.merge(data_head, biometry_head, on='ID')
data_merged.drop(columns = 'ID', inplace=True)
data_merged.to_csv('/data/kpusteln/Fetal-RL/data_preparation/data_biometry/head_biometry.csv', index=False)

/tmp/ipykernel_738255/886619127.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_head['ID'] = ID

In [34]:
# femur
ID = data_femur['index'].str.split('_').str[0]
ID = ID.astype(int)
data_femur['ID'] = ID
data_merged = pd.merge(data_femur, biometry_femur, on='ID')
data_merged.drop(columns = 'ID', inplace=True)
data_merged.to_csv('/data/kpusteln/Fetal-RL/data_preparation/data_biometry/femur_biometry.csv', index=False)

/tmp/ipykernel_738255/2055809141.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_femur['ID'] = ID